name: Build&Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    
    - run: npm ci
    
    - name: Build
      run: |
        echo VITE_API_ADDRESS= ${{ vars.VITE_API_ADDRESS }} >> .env
        npm run build --if-present
    
    - name: Get short commit SHA
      id: sha
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
          echo "SSH connection successful"
          whoami
          ls -la ~/.ssh/
    
    - name: Deploy to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: 'dist/**'
        target: '${{ vars.SITE_DIR }}/${{ steps.sha.outputs.short_sha }}'
        strip_components: 1
        debug: true
    
    - name: Create symlink to latest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ vars.SITE_DIR }}
          rm -f latest
          ln -sf ${{ steps.sha.outputs.short_sha }} latest
          #Cleanup deployments older than 3 commit
          ls -t | grep -E '^[0-9a-f]{7}$' | tail -n +4 | xargs -r rm -rf
